"""empty message

Revision ID: ea82e39342dd
Revises: 
Create Date: 2018-07-17 10:25:42.473223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea82e39342dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone_schedule', sa.Column('f', sa.Boolean(), nullable=True))
    op.add_column('zone_schedule', sa.Column('m', sa.Boolean(), nullable=True))
    op.add_column('zone_schedule', sa.Column('s', sa.Boolean(), nullable=True))
    op.add_column('zone_schedule', sa.Column('su', sa.Boolean(), nullable=True))
    op.add_column('zone_schedule', sa.Column('t', sa.Boolean(), nullable=True))
    op.add_column('zone_schedule', sa.Column('th', sa.Boolean(), nullable=True))
    op.add_column('zone_schedule', sa.Column('w', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone_schedule', 'w')
    op.drop_column('zone_schedule', 'th')
    op.drop_column('zone_schedule', 't')
    op.drop_column('zone_schedule', 'su')
    op.drop_column('zone_schedule', 's')
    op.drop_column('zone_schedule', 'm')
    op.drop_column('zone_schedule', 'f')
    # ### end Alembic commands ###
