"""Added ScheduleValve

Revision ID: f33a35b6eb94
Revises: d365012d2ac6
Create Date: 2018-07-10 09:27:26.560454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33a35b6eb94'
down_revision = 'd365012d2ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_valve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('runLength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_valve_startTime'), 'schedule_valve', ['startTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_valve_startTime'), table_name='schedule_valve')
    op.drop_table('schedule_valve')
    # ### end Alembic commands ###
